### ISSUE TITLE
Rename repo to highlightjs-dylan?

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlightjs-dylan#4]
How much of an inconvenience would it be for us to rename this repo to match all the others?

IE: `highlightjs-dylan` (adding the `js`)

**Comment by cgay** [comment]
My guess is it wouldn't be a problem, but we should probably wait until @pedro-w is done with his current changes.

**Comment by pedro-w** [comment]
I'll do that next. I don't think we're on npmjs.com so it's purely a local change as I understand it.

**Comment by pedro-w** [comment]
Done. 
Please update the URLs of any remotes you may have.

**Comment by joshgoebel** [comment]
Thanks!

**Comment by joshgoebel** [comment]
If this is linked in SUPPORTED_LANGUAGES we may need to update it there?

**Comment by pedro-w** [comment]
Good point. PR raised in highlightjs.
